# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseCli < Formula
  desc "CLI for Release (release.com)"
  homepage "https://release.com/"
  version "0.32.0-beta"

  on_macos do
    url "https://release-cli.s3.us-west-2.amazonaws.com/v0.32.0-beta/release_0.32.0-beta_Darwin_x86_64.tar.gz"
    sha256 "4e88dfdc9109b1fa220ad09c98209f7b3f2c66a8d036106c12ba71ca6c13e7c8"

    def install
      bin.install "release"

      # Install bash completion
      output = Utils.safe_popen_read(bin/"release", "completion", "bash")
      (bash_completion/"release").write output

      # Install zsh completion
      output = Utils.safe_popen_read(bin/"release", "completion", "zsh")
      (zsh_completion/"_release").write output

      # Install fish completion
      output = Utils.safe_popen_read(bin/"release", "completion", "fish")
      (fish_completion/"release.fish").write output
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the ReleaseCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://release-cli.s3.us-west-2.amazonaws.com/v0.32.0-beta/release_0.32.0-beta_Linux_arm64.tar.gz"
      sha256 "d204cb086b3585599f8168c83675ba758244c149ffb681d8d755870ee6451458"

      def install
        bin.install "release"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"release", "completion", "bash")
        (bash_completion/"release").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"release", "completion", "zsh")
        (zsh_completion/"_release").write output

        # Install fish completion
        output = Utils.safe_popen_read(bin/"release", "completion", "fish")
        (fish_completion/"release.fish").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://release-cli.s3.us-west-2.amazonaws.com/v0.32.0-beta/release_0.32.0-beta_Linux_x86_64.tar.gz"
      sha256 "a256756cbb0bb565ffa907476b45805d7ab33f40c2198193f36dd6739f3afb09"

      def install
        bin.install "release"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"release", "completion", "bash")
        (bash_completion/"release").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"release", "completion", "zsh")
        (zsh_completion/"_release").write output

        # Install fish completion
        output = Utils.safe_popen_read(bin/"release", "completion", "fish")
        (fish_completion/"release.fish").write output
      end
    end
  end
end
